package ua.naziktv.utility.client.main;

import DummyCore.Core.Core;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.client.Minecraft;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.entity.EntityList;
import net.minecraft.entity.EnumCreatureType;
import net.minecraft.item.ItemStack;
import net.minecraft.potion.Potion;
import net.minecraft.world.biome.BiomeGenBase;
import net.minecraftforge.common.MinecraftForge;
import ua.naziktv.utility.API.BlockCropsApi;
import ua.naziktv.utility.API.NLoger;
import ua.naziktv.utility.client.blocks.NBlocks;
import ua.naziktv.utility.client.enitity.FASBEntity;
import ua.naziktv.utility.client.enitity.NazikTVEntity;
import ua.naziktv.utility.client.gui.NGuiHandler;
import ua.naziktv.utility.client.items.NItems;
import ua.naziktv.utility.client.potion.Npotion;
import ua.naziktv.utility.client.potion.Potionnazikutility;

import java.io.IOException;
import java.util.ArrayList;

@Mod(modid = NMain.modid, name = NMain.name, version = NMain.version, acceptedMinecraftVersions = "1.7.10", guiFactory = "ua.naziktv.utility.client.gui.GuiFactoryNazikUt", canBeDeactivated = true)

public class NMain {

    @SidedProxy(clientSide = "ua.naziktv.utility.network.ClientProxy", serverSide = "ua.naziktv.utility.network.CommonProxy")
    public static ua.naziktv.utility.network.CommonProxy proxy;
    @Mod.Instance("nazikutility")
    public static NMain instance;

    public static final String version = "0.1.5";
    public static final String modid = "nazikutility";
    public static final String name = "NazikTV Utility Mod";
    public static final NConfig cfg = new NConfig();

    public static Potion hotarms;

    public static CreativeTabs tabNazikTV = new ua.naziktv.utility.client.main.TabNazikTV("Nazik utility");

    @EventHandler
    public void preLoad(FMLPreInitializationEvent event) {
        new NLoger().DEBUG("Start loading mod");

        instance = this;

            Core.registerModAbsolute(getClass(), name, event.getModConfigurationDirectory().getAbsolutePath(), cfg, false);

        if (NConfig.EM == true) {

            registerEntity(NazikTVEntity.class, "NazikTVEntity", 0xFFFF00, 0x7CFC00);
            proxy.registerRenderers();
            proxy.registerRenderThings();
            GameRegistry.registerTileEntity(FASBEntity.class, "tileEntityFASB");
            Npotion.register();
            NItems.registerItem();
            NBlocks.registerBlocks();
            BlockCropsApi.class.cast(NBlocks.Cotton).dropItem = new ItemStack(NItems.Cottons, 1, 0);
            BlockCropsApi.class.cast(NBlocks.Cotton).dropSeed = new ItemStack(NItems.CottonSeed, 1, 0);
            MinecraftForge.addGrassSeed(new ItemStack(NItems.CottonSeed), 13);
            Craft.Setup();
            NetworkRegistry.INSTANCE.registerGuiHandler(this, new NGuiHandler());
            MinecraftForge.EVENT_BUS.register(new nazikutEventHooks());
            MinecraftForge.EVENT_BUS.register(new DropHandler());
            FMLCommonHandler.instance().bus().register(new nazikutEventHooks());
            EntityRegistry.addSpawn(NazikTVEntity.class, 6, 1, 5, EnumCreatureType.creature,BiomeGenBase.jungle);
        }
        setupModInfo(event.getModMetadata());
    }
    @EventHandler
    public void load(FMLInitializationEvent event) {
        Minecraft.getMinecraft().getTextureManager();
        hotarms = (new Potionnazikutility(32, false, 0)).setIconIndex(0, 0).setPotionName("potion.hotarms");
    }
    @EventHandler
    public void postLoad(FMLPostInitializationEvent event){
        new NLoger().DEBUG("Stop loading mod");
    }

    public void setupModInfo(ModMetadata meta){
        ArrayList<String> authors = new ArrayList<String>();
        authors.add("NazikTV");
        meta.autogenerated = false;
        meta.modId = modid;
        meta.name = name;
        meta.version = version;
        meta.description = "Utility for NazikTV survival.";
        meta.authorList = authors;
    }

    public static void registerEntity(java.lang.Class<NazikTVEntity> entityClass, String name, int primaryColor, int secondaryColor) {
        int entityID = EntityRegistry.findGlobalUniqueEntityId();
        long seed = name.hashCode();
        EntityRegistry.registerGlobalEntityID(entityClass, name, entityID);
        EntityRegistry.registerModEntity(entityClass, name, entityID, instance, 64, 1, true);
        EntityList.entityEggs.put(Integer.valueOf(entityID), new EntityList.EntityEggInfo(entityID, primaryColor, secondaryColor));
    }

}